### ISSUE TITLE
semitone values cannot be altered

### ISSUE THREAD

**Issue by swestlake** [x42/stepseq.lv2#6]
I saw this was just updated and decided to give this a go, I noticed the plugin works nicely and if one more thing:  is it possible to set the numberic values beyond 2 semitones? I'm not sure if this is intentional or if it is really a bug.  I think it may look more like a bug, as it is a numeric value and so users should be able to change it dramatically beyond two semitones..

thanks

**Comment by x42** [comment]
Could you please rephrase that question, or elaborate? 

Every lane can send any given MIDI note 0..127.  The only constraint is that two lanes cannot use the same note (otherwise you could have duplicate note on/off messages).

The left/right arrows allow to dial in semitones, you can also use the scrollwheel: here's an example:
![semitone_mapping](https://user-images.githubusercontent.com/30246/63644591-c028ed80-c6ec-11e9-80fd-ab916b3e24fa.png)

**Comment by swestlake** [comment]
not sure what was causing it, but I was sure the values weren't overlapping.. close this thread, and i'll request it to be open if I come across it ..
