### ISSUE TITLE
MIDI input

### ISSUE THREAD

**Issue by hellocatfood** [x42/stepseq.lv2#9]
Can it be made possible to control the sequencer using midi input? For example I have a hardware midi controller and I'd like to use it to control the sequencer.

**Comment by x42** [comment]
Sadly, no; not directly.

If you could control the plugin via MIDI events, it would allow for ambiguities or conflicts with
control-ports. (e.g. you send MIDI event to turn some grid on, host sends control port automation to turn it off). 

For plugins you'll have to go via the host. e.g. in Ardour you could use MIDI-learn, however this is tedious. -- You're probably better off using a dedicated sequencer application for your MIDI controller.

**Comment by hellocatfood** [comment]
Could the solution be to have midi input be on a channel seperate from the midi output?

(my midi controller doesn't have dedicated software sadly)

**Comment by x42** [comment]
The problem is that stepseq.lv2 is a *plugin*.
stepseq.lv2 obeys to the host that loads the plugin. The host controls the plugin. So the plugin cannot by itself respond to MIDI events.

I wish I had better news or could offer a solution, but I can't. stepseq was written for the [MOD](https://www.moddevices.com/) and due to limitations of the MOD only has host controlled ports.  For the same reason it's also a fixed grid :(

In hindsight I should rather have written a generic sequencer and not care specifically about the MOD..

perhaps https://github.com/sjaehn/BSEQuencer can help you?

---

PS. It is possible to write a step-sequencer plugin that handles MIDI in/out, but in that case the plugin must not expose any controls to the host.

**Comment by hellocatfood** [comment]
Thanks for the great explanation. I think I'll go with your recommendation.
